### DISCUSSION TITLE
UID:GID issue Assistance needed

### DISCUSSION THREAD

**Discussion by Schlats** [Tzahi12345/YoutubeDL-Material#1053] [Q&A] [answered]
Hi,

I have ytdl running using docker compose on my synology nas. I noticed though that I can only get it working by using #ing out uid and gid. If I un# uid and gid, it will start but after a bit it will go from running to partial running. If I look in the log I see the below info.
I tried running this mentioned sudo command, but it will tell me "chown cannot access '/.npm' : No such file or directory". Do I need to be in a certain directory or something? I'm fairly new to all this docker stuff, but finding it fun.

Your help is much appreciated.

![ytdl error](https://github.com/Tzahi12345/YoutubeDL-Material/assets/127279525/dd2e56c5-ac6d-4c92-97c2-8c37ec317152)

Here is my compose config

```version: "2"
services:
    ytdl_material:
        environment:
            #UID: 1030
            #GID: 100
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - /volume2/docker/youtubedl/appdata:/app/appdata
            - /volume2/docker/youtubedl/audio:/app/audio
            - /volume2/docker/youtubedl/video:/app/video
            - /volume2/docker/youtubedl/users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest
    ytdl-mongo-db:
        # If you are using a Raspberry Pi, use mongo:4.4.18
        image: mongo:4
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - /volume2/docker/youtubedl/db/:/data/db

**Comment by martadinata666** [comment, marked as answer]
This should be fixed on `:nightly` tag, can you try it?

**Reply by Schlats** [reply]
how do I implement :nightly?

**Reply by martadinata666** [reply]
```
services:
    ytdl_material:
        environment:
            #UID: 1030
            #GID: 100
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - /volume2/docker/youtubedl/appdata:/app/appdata
            - /volume2/docker/youtubedl/audio:/app/audio
            - /volume2/docker/youtubedl/video:/app/video
            - /volume2/docker/youtubedl/users:/app/users
        ports:
            - "8998:17442"
        # This part, image tag
        image: tzahi12345/youtubedl-material:nightly
    ytdl-mongo-db:
        # If you are using a Raspberry Pi, use mongo:4.4.18
        image: mongo:4
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - /volume2/docker/youtubedl/db/:/data/db
```
