### DISCUSSION TITLE
Set yt-dlp as default downloader in dockerfile

### DISCUSSION THREAD

**Discussion by DrewVartanian** [Tzahi12345/YoutubeDL-Material#653] [Q&A] [answered]
How would I set the default downloader to yt-dlp when using the tzahi12345/youtubedl-material docker image?  I found the downloader setting under the advanced settings tab, but it only has youtube-dl and youtube-dlc as options. https://github.com/Tzahi12345/YoutubeDL-Material/pull/336 suggests that yt-dlp should be an option.

**Comment by GlassedSilver** [comment, marked as answer]
Make sure you're not using `latest` release, but the `nightly` releases (for now at least).

**Reply by DrewVartanian** [reply]
Thanks @GlassedSilver !  I tried switching to the nightly release, but after doing so, I could not reach the server.  I am using docker-compose with the following file:
```
version: "3.5"
services:
  youtubedl:
    image: tzahi12345/youtubedl-material:nightly
    container_name: youtubedl
    restart: "always"
    ports:
      - "8084:17442"
    volumes:
      - /volume1/docker/youtubedl/appdata:/app/appdata
      - /volume1/docker/youtubedl/audio:/app/audio
      - /volume1/docker/youtubedl/subscriptions:/app/subscriptions
      - /volume1/docker/youtubedl/users:/app/users
      - /volume1/docker/youtubedl/video:/app/video
```
If I take out the tag and rebuild, it reverts back to latest, and the server then responds at port 8084.  Any thoughts on what could be causing nightly not to work in this setup?
