### ISSUE TITLE
[BUG] docker image won't start

### ISSUE THREAD

**Issue by steffenskov** [Tzahi12345/YoutubeDL-Material#1036]
**Describe the bug**
I've been running this via `docker compose` for a while without problems, however today it suddenly won't start.

I even tried copying my compose.yaml to a different PC - with same results.
The error output is:
```
[youtubedl-material] | [entrypoint] setup permission, this may take a while
[youtubedl-material] | 
[youtubedl-material] | > backend@1.0.0 start
[youtubedl-material] | > pm2-runtime --raw pm2.config.js
[youtubedl-material] | 
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1030:65536 "/.npm"

npm ERR! A complete log of this run can be found in:
exit code: 243
```

**To Reproduce**
Create a `compose.yaml` file with this content and run `docker compose up`:

```
services:
  youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    environment:
      - UID=1030
      - GID=65536
      - USER=youtube
      - ytdl_default_downloader=yt-dlp
      - ytdl_use_local_db=true
      - ytdl_port=9998
      - write_ytdl_config=true
    ports:
      - 9998:9998/tcp
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always
```

**Expected behavior**
I expected the container to run.

**Environment**
- YoutubeDL-Material version: latest from docker hub as of writing - I don't know the exact version unfortunately.
