### ISSUE TITLE
[BUG] Docker container start fails with EACCES

### ISSUE THREAD

**Issue by AlexViridi** [Tzahi12345/YoutubeDL-Material#1075]
**Describe the bug**
I have the same bug, which is described in the second part of #1059 : latest version of youtubedl is running inside a docker-container. Unfortunately, the container can't start properly. I searched the bug history and found #1034 and #1036.  I already deleted the container and it's image and re-pulled release 4.3.2, but the logfile shows:
```
2024-01-11T12:33:37.503897093Z [entrypoint] setup permission, this may take a while
2024-01-11T12:33:57.336132695Z 
2024-01-11T12:33:57.336145619Z > backend@1.0.0 start
2024-01-11T12:33:57.336148755Z > pm2-runtime --raw pm2.config.js
2024-01-11T12:33:57.336151592Z 
2024-01-11T12:33:57.434153361Z npm ERR! code EACCES
2024-01-11T12:33:57.434487877Z npm ERR! syscall mkdir
2024-01-11T12:33:57.434757544Z npm ERR! path /.npm
2024-01-11T12:33:57.435061230Z npm ERR! errno -13
2024-01-11T12:33:57.435844526Z npm ERR! 
2024-01-11T12:33:57.435954882Z npm ERR! Your cache folder contains root-owned files, due to a bug in
2024-01-11T12:33:57.436023151Z npm ERR! previous versions of npm which has since been addressed.
2024-01-11T12:33:57.436104361Z npm ERR! 
```
The logfile suggest to chown the cache folder, but unfortunately, I can't connect to the container, docker says that it's still restarting. Also changing the restart policy didn't help.
It's been a while since I succesfully used youtubedl the last time. So I'm not sure since which release it refuses to work.
Your help is very appreciated!

**To Reproduce**
Docker-Compose:
```
# Proxy Network and Security
x-network-and-security: &network-and-security
  networks:
    - t2_proxy
  security_opt:
    - no-new-privileges:true

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  <<: *network-and-security
  restart: unless-stopped

  youtubedl-material:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    volumes:
      - $DOCKERDIR/appdata/youtubedl-material/config:/app/appdata
      - $DATADIR/downloads/youtubedl-material/audio:/app/audio
      - $DATADIR/downloads/youtubedl-material/video:/app/video
      - $DATADIR/downloads/youtubedl-material/subscriptions:/app/subscriptions
      - $DOCKERDIR/appdata/youtubedl-material/users:/app/users
    environment:
      UID: $PUID
      GID: $PGID
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.youtubedl-material-rtr.entrypoints=https"
      - "traefik.http.routers.youtubedl-material-rtr.rule=Host(`ytdl.$DOMAINNAME`)"
      - "traefik.http.routers.youtubedl-material-rtr.tls=true"
    ## Middlewares
      - "traefik.http.routers.youtubedl-material-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.youtubedl-material-rtr.service=youtubedl-material-svc"
      - "traefik.http.services.youtubedl-material-svc.loadbalancer.server.port=17442"
```
All volumes are chowned to the docker user and group.

**Expected behavior**
The container starts without errors and I can use youtubedl.

**Environment**
- YoutubeDL-Material version 4.3.2
