### ISSUE TITLE
[BUG] Shows plain HTML after upgrading to Traefik v3

### ISSUE THREAD

**Issue by kladderadeng** [Tzahi12345/YoutubeDL-Material#1125]
First: I upgraded all Containers to run via Traefik v3 now and this so far is the only one showing an issue. Please don't hit me if it turns out this is the wrong place to ask for help ;-)

**Describe the bug**
After upgrading my reverse proxy to Traefik v3, when opening the ytdl-material frontend, it only shows plain HTML in the browser.

**To Reproduce**
1. Use docker compose to host ytdl-material via Traefik v3 like so:
```
services:
  ytdl_material:
    container_name: ytdl-material
    hostname: ytdl-material
    image: tzahi12345/youtubedl-material:latest
    restart: unless-stopped
    environment:
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
      UID: 1000
      GID: 1000
    depends_on:
      - ytdl-mongo-db
    volumes:
      - /opt/ytdl-material/appdata:/app/appdata
      - /opt/ytdl-material/audio:/app/audio
      - /opt/ytdl-material/video:/app/video
      - /opt/ytdl-material/subscriptions:/app/subscriptions
      - /opt/ytdl-material/users:/app/users
    labels:
      - "traefik.enable=true"
      - "traefik.publish=lan"
      - "traefik.http.routers.ytdl-material.entrypoints=https"
      - "traefik.http.routers.ytdl-material.rule=Host(`ytdl.my.domain`)"
      - "traefik.http.routers.ytdl-material.tls=true"
      - "traefik.http.routers.ytdl-material.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ytdl-material.middlewares=default@file"
      - "traefik.http.routers.ytdl-material.service=ytdl-material"
      - "traefik.http.services.ytdl-material.loadbalancer.server.port=443"
      - "traefik.docker.network=docker_trusted"
    networks:
      - docker_trusted

  ytdl-mongo-db:
    container_name: ytdl-mongodb
    hostname: ytdl-mongodb
    image: mongo:4
    restart: unless-stopped
    logging:
      driver: "none"
    environment:
      UID: 1000
      GID: 1000
    volumes:
      - /opt/ytdl-material/db:/data/db
      - /opt/ytdl-material/configdb:/data/configdb
    networks:
      - docker_trusted

networks:
  docker_trusted:
    name: docker_trusted
    external: true
```

3. Try to access ytdl-material via https

**Expected behavior**
I expected to see the ytdl-material GUI like before the upgrade.

**Screenshots**
This is how it looks rendered in a Chromium based browser:
![image](https://github.com/user-attachments/assets/22b25773-35f9-479d-9276-13a1ebead35c)

There is no error popping up after the container is started and when refreshing the website with F5:
![image](https://github.com/user-attachments/assets/ec04e9aa-e0e9-4dec-869a-99b46b36c90d)

**Environment**
- YoutubeDL-Material version v4.3.2
- Docker tag:latest
