### ISSUE TITLE
Can't Setup subtitles, need SRT format for VLC media player on  Windows 11 Host Machine

### ISSUE THREAD

**Issue by TeomanEgeSelcuk** [Tzahi12345/YoutubeDL-Material#1130]
Here's the updated issue text incorporating the additional details:

### Issue Title:
Subtitles not working, need SRT format for Windows 11 and VLC

### Issue Description:
I am unable to get subtitles to work with YoutubeDL-Material. I need the subtitles to be in SRT format as I am using a Windows 11 machine and VLC media player.

#### Configuration Details:
- **Operating System:** Windows 11
- **Media Player:** VLC
- **Docker Configuration:**
  ```yaml
  version: "2"
  services:
    ytdl_material:
      environment: 
        ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
        ytdl_use_local_db: 'false'
        write_ytdl_config: 'true'
        YTDL_FORMAT: 'bestvideo[height<=1080]+bestaudio/best[height<=1080]'
        YTDL_SUBTITLES_LANG: 'en'
        YTDL_SUBTITLES_AUTO: 'true'
        YTDL_POSTPROCESSORS: '[{"key": "FFmpegSubtitlesConvertor", "format": "srt"}]'
      restart: always
      depends_on:
        - ytdl-mongo-db
      volumes:
        - ./appdata:/app/appdata
        - ./audio:/app/audio
        - ./video:/app/video
        - ./subscriptions:/app/subscriptions
        - ./users:/app/users
      ports:
        - "8998:17442"
      image: tzahi12345/youtubedl-material:latest

    ytdl-mongo-db:
      image: mongo:4
      logging:
        driver: "none"
      container_name: mongo-db
      restart: always
      volumes:
        - ./db/:/data/db
  ```

#### default.json:
  ```json
  {
    "YoutubeDLMaterial": {
      "Host": {
        "url": "http://example.com",
        "port": "17442"
      },
      "Downloader": {
        "path-audio": "audio/",
        "path-video": "video/",
        "default_file_output": "",
        "use_youtubedl_archive": false,
        "custom_args": "--write-sub --sub-lang en --convert-subs srt",
        "include_thumbnail": true,
        "include_metadata": true,
        "max_concurrent_downloads": 5,
        "download_rate_limit": ""
      },
      "Extra": {
        "title_top": "YoutubeDL-Material",
        "file_manager_enabled": true,
        "allow_quality_select": true,
        "download_only_mode": false,
        "force_autoplay": false,
        "enable_downloads_manager": true,
        "allow_playlist_categorization": true,
        "enable_notifications": true,
        "enable_all_notifications": true,
        "allowed_notification_types": [],
        "enable_rss_feed": false
      },
      "API": {
        "use_API_key": false,
        "API_key": "",
        "use_youtube_API": false,
        "youtube_API_key": "",
        "twitch_auto_download_chat": false,
        "use_sponsorblock_API": false,
        "generate_NFO_files": false,
        "use_ntfy_API": false,
        "ntfy_topic_URL": "",
        "use_gotify_API": false,
        "gotify_server_URL": "",
        "gotify_app_token": "",
        "use_telegram_API": false,
        "telegram_bot_token": "",
        "telegram_chat_id": "",
        "webhook_URL": "",
        "discord_webhook_URL": "",
        "slack_webhook_URL": ""
      },
      "Themes": {
        "default_theme": "default",
        "allow_theme_change": true
      },
      "Subscriptions": {
        "allow_subscriptions": true,
        "subscriptions_base_path": "subscriptions/",
        "subscriptions_check_interval": "86400",
        "redownload_fresh_uploads": false
      },
      "Users": {
        "base_path": "users/",
        "allow_registration": true,
        "auth_method": "internal",
        "ldap_config": {
          "url": "ldap://localhost:389",
          "bindDN": "cn=root",
          "bindCredentials": "secret",
          "searchBase": "ou=passport-ldapauth",
          "searchFilter": "(uid={{username}})"
        }
      },
      "Database": {
        "use_local_db": false,
        "mongodb_connection_string": "mongodb://ytdl-mongo-db:27017"
      },
      "Advanced": {
        "default_downloader": "yt-dlp",
        "use_default_downloading_agent": true,
        "custom_downloading_agent": "",
        "multi_user_mode": false,
        "allow_advanced_download": false,
        "use_cookies": false,
        "jwt_expiration": 86400,
        "logger_level": "info"
      }
    }
  }
  ```

I have followed all the installation instructions, and they have worked perfectly. Videos can be downloaded without any issues. However, I can't get the subtitles to work. That's the only issue I am facing.

Despite these settings, the subtitles are not being downloaded or converted to SRT format. Any help resolving this issue would be greatly appreciated.

### Steps to Reproduce:
1. Set up `YoutubeDL-Material` using the provided `docker-compose.yml`.
2. Configure the `default.json` as shown.
3. Attempt to download a YouTube video with subtitles.

Thank you for your assistance!
