### ISSUE TITLE
Docker install errors

### ISSUE THREAD

**Issue by maltokyo** [Tzahi12345/YoutubeDL-Material#14]
I get this error after the initial image build:

```
root@ssd:~/zDocker/docker-YoutubeDL-Tzahi12345# docker-compose up
Recreating ytdl_material ... done
Attaching to ytdl_material
ytdl_material    | internal/modules/cjs/loader.js:796
ytdl_material    |     throw err;
ytdl_material    |     ^
ytdl_material    | 
ytdl_material    | Error: Cannot find module '/app/app.js'
ytdl_material    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
ytdl_material    |     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
ytdl_material    |     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
ytdl_material    |     at internal/main/run_main_module.js:17:11 {
ytdl_material    |   code: 'MODULE_NOT_FOUND',
ytdl_material    |   requireStack: []
ytdl_material    | }
```

**Comment by gerroon** [comment]
I have the same issue on Debian Testing

**Comment by Tzahi12345** [comment]
Interesting, are you using the latest `docker-compose.yml` file from the [latest release](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v3.3)? I'm having a hard time replicating this error.

**Comment by gerroon** [comment]
Here is my compose file

https://bin.privacytools.io/?dbcb4689efcf04fd#gcHvb0/cCkD2bjbvHBJFWajAHiGrmUuixBXCje1OYcA=

**Comment by maltokyo** [comment]
Here is mine:

```
version: "2"
services:
    ytdl_material:
        container_name: ytdl_material
        build: .
        environment: 
            # config items
            ytdl_url: http://localhost:8998
            ytdl_port: '17442'
            ytdl_use_encryption: 'false'
            ytdl_cert_file_path: /etc/letsencrypt/live/example.com/fullchain.pem
            ytdl_key_file_path: /etc/letsencrypt/live/example.com/privkey.pem
            ytdl_audio_folder_path: audio/
            ytdl_video_folder_path: video/
            ytdl_title_top: Web_Video_Downloader
            ytdl_file_manager_enabled: 'true'
            ytdl_allow_quality_select: 'true'
            ytdl_download_only_mode: 'false'
            ytdl_allow_multi_download_mode: 'true'
            ytdl_use_youtube_api: 'false'
            ytdl_youtube_api_key: 'false'
            ytdl_default_theme: default
            ytdl_allow_theme_change: 'true'
            ytdl_use_default_downloading_agent: 'true'
            ytdl_custom_downloading_agent: 'false'
            ytdl_allow_advanced_download: 'false'
            # do not touch this
            write_ytdl_config: 'true'
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: unless-stopped
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:3.3
        volumes:
            - '/var/lib/docker/volumes/ytdl_material/_data_ytdl_audio:/audio'
            - '/var/lib/docker/volumes/ytdl_material/_data_ytdl_video:/video'
networks:
  default:
    external:
      name: webproxy
```
