### ISSUE TITLE
The videos are not in the volume mapping  

### ISSUE THREAD

**Issue by gerroon** [Tzahi12345/YoutubeDL-Material#16]
HI

I am having a weird issue. I used volume mapping as below. `/media/YOUTUBE` is a samba drive with proper permissions.

```
            ytdl_audio_folder_path: audio/
            ytdl_video_folder_path: video/


       volumes:
            - /media/YOUTUBE:/app/audio
            - /media/YOUTUBE:/app/video

```

When I download any video I see that `info.json` is written to thta folder but I cant find the actual videos themselves in that folder. Is it possible that the videos are not saved in that folder at all?

I also logged into the container and I see that `/app/video` is actually `/media/YOUTUBE` so that idea is working. 

The videos are watchable as far as I can tel, so it is clear that they are saved somewhere, but where? Because they are not in the named volume
