### ISSUE TITLE
Dockerfile in root of repository

### ISSUE THREAD

**Issue by mattheys** [Tzahi12345/YoutubeDL-Material#167]
Hi I'd like to try this out but I run on Aarch64 (Arm64) and your docker image is only Amd64, if the dockerfile is in the root of the github then I can do a docker-compose something like this with the build tag instead of image tag.

```
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        build: https://github.com/Tzahi12345/YoutubeDL-Material.git
```
