### ISSUE TITLE
Docker image for arm architecture

### ISSUE THREAD

**Issue by tam481** [Tzahi12345/YoutubeDL-Material#188]
Hello,
Would you consider releasing a multi-arch image on Docker Hub? I would like to run it on my Raspberry Pi

Thank you in advance

**Comment by Tzahi12345** [comment]
There's an official Dockerfile [here](https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/master/backend/Dockerfile-armhf), you'll have to build the image yourself as I haven't gotten a chance to set up autobuilds (I need to add proper Qemu support for the Dockerfile for Docker Hub). Thankfully, building it youself is quite easy. This modified docker-compose.yml will build it for you with `Dockerfile-armf` in the same folder:

```
version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        build:
            context: https://github.com/Tzahi12345/YoutubeDL-Material.git#master:backend
            dockerfile: ./Dockerfile-armhf
        image: tzahi12345/youtubedl-material:latest
```

It builds straight from GitHub and uses the official ARM Dockerfile to run. Run `docker-compose build` and then `docker-compose up` to start it up.

I admittedly haven't tested it officially, so let me know how it works!
