### ISSUE TITLE
ARM builds broken

### ISSUE THREAD

**Issue by frezeen** [Tzahi12345/YoutubeDL-Material#200]
rpi4, docker, installed from nightly
first run i dont have access to all options in UI
https://youtu.be/NEkSKtG9HPM

**Comment by Tzahi12345** [comment]
Can you go into the console (right click->inspect element->console) and see if any errors show up there?

**Comment by frezeen** [comment]
ERROR TypeError: Cannot read property 'use-encryption' of undefined
    at XS (1-es2015.2215af2b4dddea84e38f.js:1)
    at ao (main-es2015.63a61681b752f95b7352.js:1)
    at uo (main-es2015.63a61681b752f95b7352.js:1)
    at main-es2015.63a61681b752f95b7352.js:1
    at uo (main-es2015.63a61681b752f95b7352.js:1)
    at main-es2015.63a61681b752f95b7352.js:1
    at uo (main-es2015.63a61681b752f95b7352.js:1)
    at Ro (main-es2015.63a61681b752f95b7352.js:1)
    at main-es2015.63a61681b752f95b7352.js:1
    at uo (main-es2015.63a61681b752f95b7352.js:1)

everytime i move mouse without click on page i got lots errors

**Comment by Tzahi12345** [comment]
Looks like the frontend version was mismatched with the backend, I went ahead and pushed a hotfix until autobuilds for ARM are figured out, `nightly-arm` should work without issue now!

**Comment by frezeen** [comment]
sorry for delay, cant test it, becouse i got this error now when try to pull and up tzahi12345/youtubedl-material:nightly-arm.

root@DietPi:~# docker-compose up
Starting root_ytdl_material_1 ... error

ERROR: for root_ytdl_material_1  Cannot start service ytdl_material: b'OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \\"/app/entrypoint.sh\\": stat /app/entryt.sh: no such file or directory": unknown'

ERROR: for ytdl_material  Cannot start service ytdl_material: b'OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \\"/app/entrypoint.sh\\": stat /app/entrypoint.so such file or directory": unknown'
ERROR: Encountered errors while bringing up the project.

**Comment by Tzahi12345** [comment]
I see what went wrong, I forgot to include `entrypoint.sh` in my manual build. I went ahead and pushed a fixed version, can you try pulling again and see if it works now?

Thanks!

**Comment by frezeen** [comment]
root@DietPi:~# docker-compose up
Creating root_ytdl_material_1 ... done
Attaching to root_ytdl_material_1
ytdl_material_1  | standard_init_linux.go:211: exec user process caused "no such                    file or directory"
root_ytdl_material_1 exited with code 1

**Comment by Tzahi12345** [comment]
Latest won't work as it's for x86, nightly-arm should.. I'll go ahead and reopen since it's clearly broken. You can try running `docker-compose build` on the attached file: [docker-compose.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/5125421/docker-compose.zip) (had to zip it up for GitHub)

It's just a modified docker-compose.yml that looks like this:

```
version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        build:
            context: https://github.com/Tzahi12345/YoutubeDL-Material.git#working-arm:backend
            dockerfile: ./Dockerfile-armhf
        image: tzahi12345/youtubedl-material:latest


```

That should work for now. In the meantime I'll work on getting a permanent solution up. I appreciate the logs!
