### ISSUE TITLE
Synology ACL and docker volumes

### ISSUE THREAD

**Issue by ratheile** [Tzahi12345/YoutubeDL-Material#208]
I am trying to debug an issue with ACL (in this case synoacl) based volumes for audio / video.

```
version: "2"
services:
    ytdl_material:
        environment:
            UID: 1024
            GID: 100
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - /volume1/docker/youtube-dl/appdata:/app/appdata
            - /volume1/music/managed/youtube:/app/audio
            - /volume1/video/managed/youtube:/app/video
            - /volume1/docker/youtube-dl/subscriptions:/app/subscriptions
            - /volume1/docker/youtube-dl/users:/app/users
        ports:
            - "17442:17442"
        image: tzahi12345/youtubedl-material:nightly
```
is my docker-compose script the user 1024:100 maps to synology's `admin`:`users`.

On first startup YDLM( YoutubeDL-Material) manages to initialize itself using this configuration, the `appdata` folder works just fine. On the host, ACL permissions persist and the user/group matches for files in this folder.

However, for `/app/audio` and `/app/video` the docker-internal user `youtube` has no access. An error shows:

```
(node:1) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, scandir 'audio/'
    at Object.readdirSync (fs.js:955:3)
    at recFindByExt (/app/utils.js:163:25)
    at Object.getDownloadedFilesByType (/app/utils.js:28:25)
    at /app/db.js:187:29
    at Array.forEach (<anonymous>)
    at Object.importUnregisteredFiles (/app/db.js:185:19)
    at /app/app.js:578:16
    at new Promise (<anonymous>)
    at loadConfig (/app/app.js:561:12)
    at Object.<anonymous> (/app/app.js:185:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

if I inspect the container, it is clear why:

![image](https://user-images.githubusercontent.com/2394878/91827284-e7d75d80-ec3e-11ea-9460-94db3db69094.png)

I can now change the permissions inside of the container to 755 to make YTDM work but this alters the folder permissions on the host as well, dropping any ACL permissions which means the folder is most likely incompatible with other software such as a media center crawling that directory.

I am looking for advice to understand why permissions are fine for the `appdata` dir - showing read write execute access conceptionally - but not for the media directories.

Thanks!
