### ISSUE TITLE
[Docker Nightly] Permission broken, UID/GID not working, overwritten with standard 1000:1000

### ISSUE THREAD

**Issue by quorn23** [Tzahi12345/YoutubeDL-Material#361]
The UID and GID env with docker are getting ignored with the current image.

This has been done with a fresh install, so empty config dir etc.
For example i have an user "docker" in the group "users" or in digits 1028:100

For the downloads i create a directory /data/youtube
Before the run of the container the permissions are docker:users as they are supposed to be.
Container runs with following log output:

`warn:    --minUptime not set. Defaulting to: 1000ms`
`warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms`
`INFO: Beginning migration: 4.1->4.2+`
`ERROR: EACCES: permission denied, scandir 'audio/'`
`ERROR: Migration failed: 4.1->4.2+`
`INFO: youtube-dl successfully updated!`
`INFO: YoutubeDL-Material v4.2 started on PORT 17442`
```
(node:20) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, scandir 'audio/'
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
`(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
`(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
`(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

If i look at the permissions now /data/youtube has 1000:1000
the config directory gets set to 1000:1000 as well.

This breaks it for anyone using 
```
      - PUID=not1000
      - PGID=not1000
```

**Comment by Tzahi12345** [comment]
Related issues: #186 #208

I'll try to see if I can find out what is preventing the local Docker user from modifying those files, unfortunately I'm not an expert on ACL so it will be a bit of trial and error on my part to hone down where the problem really is (really it's just a logic problem in the Dockerfile/entrypoint.sh)

@SuperSandro2000 any thoughts?

**Comment by SuperSandro2000** [comment]
Right now you can't change the user or group ID of the user via envs. See https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/Dockerfile#L20

Give the files access for group 1000 or user 1000 should fix it.

**Comment by quorn23** [comment]
Thanks to bugging @HalianElf in Discord he had a look and managed to help me getting it working. 

I will try to condense the conversation.

So the issue is, "forever" runs in the container with the user youtube with the id 1000. Once we change the id, it can't find any home dir and tries to create it in root.

To battle that he asked me to add `FOREVER_ROOT=/app/.forever` to my envs in my docker-compose.
Now YTDL-Material creates the files properly without any errors with the correct user.

Suggested fixes
Either add the FOREVER_ROOT to the dockerfile, or we could use it in a path variable. Maybe there is an even simpler solution, as you know "forever" probably better @Tzahi12345

**Comment by Tzahi12345** [comment]
Sounds like a simple fix! I've gone ahead and added that fix to master.

We do want to use forever as it allows us to restart the server internally, it essentially wraps the app within a separate program. Otherwise things get messy.

Anyways, let me know if this is fixed in the latest nightly! Thanks for doing some of the debugging/fixing work for me as I've been wayyy too busy lately :)

**Comment by quorn23** [comment]
`today at 2:05:10 AM  warn:    --minUptime not set. Defaulting to: 1000ms`
`today at 2:05:10 AM  warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms`
`today at 2:05:22 AM  2021-05-17T00:05:22.049Z INFO: Cannot find config file. Creating one with default values...`
`today at 2:05:22 AM  2021-05-17T00:05:22.116Z INFO: Beginning migration: 4.1->4.2+`
`today at 2:05:22 AM  2021-05-17T00:05:22.140Z INFO: 4.1->4.2+ migration complete!`
`today at 2:05:23 AM  2021-05-17T00:05:23.189Z INFO: youtube-dl successfully updated!`
`today at 2:05:23 AM  2021-05-17T00:05:23.202Z INFO: YoutubeDL-Material v4.2 started on PORT 17442`

Quickly renamed the folder and removed the env in my docker-compose and spun it up. Looks like we're back on track and the image is working again with non standard 1000:1000 user/group.

Now merge #336 and i'm happy ;) I will close the issue as it works now as intended.

**Comment by Tzahi12345** [comment]
#336 is merged!

**Comment by ckykenken** [comment]
The UID and GID env with docker are getting ignored again, with no output log! My stack:

```version: "2"
services:
    ytdl_material:
        environment: 
            UID: 1000
            GID: 1000
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - /srv/dev-disk-by-label-files/Appdata/ytdlm/appdata:/app/appdata
            - /srv/dev-disk-by-label-files/Appdata/ytdlm/Video:/app/video
            - /srv/dev-disk-by-label-files/Appdata/ytdlm/subscriptions:/app/subscriptions
            - /srv/dev-disk-by-label-files/Appdata/ytdlm/users:/app/users
            - /srv/dev-disk-by-label-files/Appdata/ytdlm/Audio:/app/audio
        ports:
            - 17442:17442
        image: tzahi12345/youtubedl-material:latest```

**Comment by Tzahi12345** [comment]
@ckykenken would you mind trying the `nightly` tag instead? It's a year and change newer, v4.3 will drop fairly soon and then you can go back to `latest`

**Comment by GAS85** [comment]
Hey, Permission issue is Back, container will not even start with a fresh folder if `GID` and `PID` are set with `latest` and `nightly` tags.
My Config:

```yaml
version: "3.7"
services:

  ytdl_material:
#    image: tzahi12345/youtubedl-material:latest
    image: tzahi12345/youtubedl-material:nightly
    restart: unless-stopped
    container_name: ytdl_material
    environment:
      - ytdl_use_local_db=true
      - write_ytdl_config=false
      - ALLOW_CONFIG_MUTATIONS=false
      - ytdl_default_downloader=yt-dlp
      - UID=1001
      - GID=119
    volumes:
      - ${WORKINGDIR}/docker/youtubedl-material/appdata:/app/appdata
      - ${WORKINGDIR}/docker/youtubedl-material/subscriptions:/app/subscriptions
      - ${WORKINGDIR}/docker/youtubedl-material/users:/app/users
      - ${WORKINGDIR}/Downloads/completed/music/YouTube_audio:/app/audio
      - ${WORKINGDIR}/Downloads/completed/Videos_Photos/YouTube_video:/app/video
    ports:
      - 9011:17442
    healthcheck:
      test: curl -f http://localhost:17442 || exit 1
      interval: 5m00s
      timeout: 5s
      retries: 2
      start_period: 30s
    labels:
      - autoheal=true
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
```

Fresh install Error:

```
2023-05-22T06:55:28: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-

2023-05-22T06:55:28: PM2 log: App [YoutubeDL-Material:0] online

Error: EACCES: permission denied, mkdir 'appdata/logs'

    at Object.mkdirSync (node:fs:1336:3)

    at File._createLogDirIfNotExist (/app/node_modules/winston/lib/winston/transports/file.js:691:10)

    at new File (/app/node_modules/winston/lib/winston/transports/file.js:92:28)

    at Object.<anonymous> (/app/logger.js:17:7)

    at Module._compile (node:internal/modules/cjs/loader:1103:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19)

    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39) {

  errno: -13,

  syscall: 'mkdir',

  code: 'EACCES',

  path: 'appdata/logs'

}

2023-05-22T06:55:28: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]

2023-05-22T06:55:28: PM2 log: Script /app/app.js had too many unstable restarts (16). Stopped. "errored"

2023-05-22T06:55:31: PM2 log: 0 application online, retry = 3
```

And Folders will be created as `root`:

```
ll -R youtubedl-material/
youtubedl-material/:
total 20
drwxr-xr-x+  5 root root 4096 May 22 08:50 ./
drwxr-xr-x+ 33 root root 4096 May 22 08:50 ../
drwxr-xr-x+  2 root root 4096 May 22 08:50 appdata/
drwxr-xr-x+  2 root root 4096 May 22 08:50 subscriptions/
drwxr-xr-x+  2 root root 4096 May 22 08:50 users/

youtubedl-material/appdata:
total 8
drwxr-xr-x+ 2 root root 4096 May 22 08:50 ./
drwxr-xr-x+ 5 root root 4096 May 22 08:50 ../

youtubedl-material/subscriptions:
total 8
drwxr-xr-x+ 2 root root 4096 May 22 08:50 ./
drwxr-xr-x+ 5 root root 4096 May 22 08:50 ../

youtubedl-material/users:
total 8
drwxr-xr-x+ 2 root root 4096 May 22 08:50 ./
drwxr-xr-x+ 5 root root 4096 May 22 08:50 ../
```
