### ISSUE TITLE
[BUG] Can't running docker container

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#402]
not working docker nightly version

```
os: ubuntu server 20.04
docker: Docker version 20.10.7, build f0df350
docker-compose: docker-compose version 1.29.2, build 5becea4c
```

docker-compose.yml here
```
version: "2"
services:
    ytdl_material:
        container_name: youtubedl
        image: tzahi12345/youtubedl-material:nightly
        environment:
            ALLOW_CONFIG_MUTATIONS: "true"
        restart: always
        volumes:
            - /data/youtubedl/appdata:/app/appdata
            - /data/youtubedl/Youtube/audio:/app/audio
            - /data/youtubedl/Youtube/video:/app/video
            - /data/youtubedl/Youtube/subscriptions:/app/subscriptions
            - /data/youtubedl/users:/app/users
        ports:
            - "8998:17442"
```

result here
```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
/app/config.js:78
        logger.error('Failed to get config file');
               ^

TypeError: Cannot read property 'error' of null
    at getConfigFile (/app/config.js:78:16)
    at Object.getConfigItem (/app/config.js:93:23)
    at Object.<anonymous> (/app/db.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/app.js:15:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error: Forever detected script exited with code: 1
```
stuck here.
can I try any fix?
