### ISSUE TITLE
[BUG] The same video is displayed in several. 

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#415]
**Describe the bug**
The webpage is not responding.
The same video is displayed in several. 

**To Reproduce**
1. git clone https://github.com/Tzahi12345/YoutubeDL-Material.git
2. docker build -t ytdl:0.1 .
3. edit docker-compose.yml file (container name, mount path)
4. goto YTDL setting. select yt-dlp, use cookies
5. then Subscribe to about 15 channels. (It happened when I subscribed to a new channel or new video)
6. After a few hours the webpage becomes unresponsive.
7. So I restarted the container.

**Expected behavior**
The same video appears.

**Screenshots**
![55](https://user-images.githubusercontent.com/6009737/128521045-efc0ee4f-b46c-43e1-85ec-10de111a60e4.png)

**Environment**
- After downloading git clone, I made an image with docker build.

**Additional context**
I don't know if it's a virtual machine problem or a Docker problem.
(I'm running an Ubuntu virtual machine on xcp-ng, and I've set up 6 cpu and 8 GB of ram. Also, I am using a Synology NAS, and it is mounted through smb.)
The webpage goes unresponsive within a few hours of running the container.
So I had no choice but to restart the container. I don't know if that's the reason, but the same video appears multiple times. 
```
version: "2"
services:
    ytdl_material:
        environment:
            ALLOW_CONFIG_MUTATIONS: 'true'
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - /mnt/z/audio:/app/audio
            - /mnt/z/video:/app/video
            - /mnt/z/subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        container_name: ytdl
        image: ytdl:0.1
    ytdl-mongo-db:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        logging:
            driver: "none"
        container_name: mongo-db
        volumes:
            - ./db/:/data/db
```
