### ISSUE TITLE
[BUG] - Audio does not download with video

### ISSUE THREAD

**Issue by modem7** [Tzahi12345/YoutubeDL-Material#438]
**Describe the bug**
Videos do not download with audio, only video.

**To Reproduce**
Video: https://www.youtube.com/watch?v=VWDpWmc5Yys
![image](https://user-images.githubusercontent.com/4349962/132230554-8fcc0ea3-95d5-41be-99a8-0b20cacac08a.png)

**Expected behavior**
Video downloaded w/ audio

**Screenshots**

**Environment**
```yaml
  ytdl_material:
    container_name: YTDL_Material
    image: tzahi12345/youtubedl-material:nightly
    volumes:
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/appdata:/app/appdata
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/audio:/app/audio
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/video:/app/video
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/subscriptions:/app/subscriptions
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/users:/app/users
    environment: 
      ALLOW_CONFIG_MUTATIONS: 'true'
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
      UID: $PUID
      GID: $PGID
    networks:
      - isonet
    ports:
      - "8998:17442"
    restart: always
```

JSON attached
[video.info.json.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/7116547/video.info.json.zip)
