### ISSUE TITLE
[BUG] Successful test connection but failure to transfer DB to MongoDB

### ISSUE THREAD

**Issue by yllekz** [Tzahi12345/YoutubeDL-Material#510]
**Describe the bug**
I upgraded my YoutubeDL-Material container to utilize MongoDB. I used the docker-compose sample to get the containers going. When I go to settings->database and go to "test connection string" it says it's successful, however upon clicking "Transfer DB to MongoDB" I get this error: ``Failed to transfer DB -- transfer was aborted. Error: Failed to transfer DB as it cannot transition into its current status: MongoDB`` - no other errors to go by.

**To Reproduce**
1. Go to Settings->Database
2. Click on 'Test connection String' and observe the successful connection
3. Click on 'Transfer DB to MongoDB' and get the error above

**Expected behavior**
Database should transfer

**Screenshots**
n/a

**Environment**
- OS: macOS Big Sur on M1 architecture running Docker Desktop
- YoutubeDL-Material version: v4.2
- Docker tag: nightly (optional)

**Additional context**
Docker-compose file:

```
version: "2"
services:
    ytdl_material:
        image: tzahi12345/youtubedl-material:nightly
        restart: unless-stopped
        environment:
            UID: '501'
            GID: '20'
            ALLOW_CONFIG_MUTATIONS: 'true'
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        volumes:
            - "/Users/me/docker/config/ytdlmaterial:/app/appdata"
            - "/Volumes/extvol1/docker/data/ytdlmaterial/video:/app/video"
            - "/Volumes/extvol1/docker/data/ytdlmaterial/audio:/app/audio"
            - "/Volumes/extvol1/docker/data/ytdlmaterial/subscriptions:/app/subscriptions"
            - "/Volumes/extvol1/docker/data/ytdlmaterial/users:/app/users"
        ports:
            - "17442:17442"
    ytdl-mongo-db:
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: "local"          
        container_name: mongo-db
        restart: unless-stopped
        volumes:
            - "/Users/me/docker/config/ytdlmaterialdb:/data/db"
```
