### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by pinkworld123** [Tzahi12345/YoutubeDL-Material#614]
Hello, 

I try to run image from docker hub and i got this error .ERROR: connect ECONNREFUSED 127.0.0.1:27017

my docker-compose.yml

```
version: 3.7
services:
  ytdl_material:
    image: tzahi12345/youtubedl-material:nightly
    container_name: youtubedl-material
    restart: unless-stopped
    volumes:
      - ./data/appdata:/app/appdata
      - ./data/audio:/app/audio
      - ./data/video:/app/video
      - ./data/subscriptions:/app/subscriptions
      - ./data/users:/app/users
    environment:
      UID: 1006
      GID: 1006
      ALLOW_CONFIG_MUTATIONS: 'true'
    ports:
      - 17442:17442
    networks:
      - youtubedl-material   


```

**Comment by MattNer0** [comment]
Hello,
I was having the same problem so I checked the docker-compose.yml from the repo [here](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/docker-compose.yml) and noticed that the mongodb instance was moved to another container.

I guess you can try to play with the env `ytdl_mongodb_connection_string` or `ytdl_use_local_db`, but I didn't test it.
In my case I just recreated both containers using the updated `docker-compose.yml` from the repo.

Cheers

**Comment by GlassedSilver** [comment]
> Hello, I was having the same problem so I checked the docker-compose.yml from the repo [here](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/docker-compose.yml) and noticed that the mongodb instance was moved to another container.
> 
> I guess you can try to play with the env `ytdl_mongodb_connection_string` or `ytdl_use_local_db`, but I didn't test it. In my case I just recreated both containers using the updated `docker-compose.yml` from the repo.
> 
> Cheers

YTDL-M never included a MongoDB backend within its own container and therefore nothing got ever moved.

What we used before was a single `.json` file as our "local db". By contrast, MongoDB can be put anywhere, even on a different physical host - or in the case of a `docker-compose.yml` file: in a separate container.

When the variable to configure MongoDB got introduced, that was the time when we actually enabled to use it to begin with.

That being said, maybe your reply helps @pinkworld123 out, thank you for your feedback.

If this doesn't get resolved, please don't hesitate to comment further, we're absolutely happy to help! 👍

**Comment by pinkworld123** [comment]
Thanks for reply. 

@GlassedSilver I was debugging and found that by default tries to connect to mongodb and when its not found after few retries it uses json. 

So basically default image is working fine just need to wait few minutes.

**Comment by sunjam** [comment]
The [docker-compose.yml](https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/master/docker-compose.yml) does not work for me when attempting to use mongo.

```
getaddrinfo EAI_AGAIN ytdl-mongo-db
ECONNREFUSED 127.0.0.1:27017
Failed to connect to MongoDB, using Local DB as a fallback. Make sure your MongoDB instance is accessible, or set Local DB as a default through the config.
```

**Comment by GlassedSilver** [comment]
> Thanks for reply.
> 
> @GlassedSilver I was debugging and found that by default tries to connect to mongodb and when its not found after few retries it uses json.
> 
> So basically default image is working fine just need to wait few minutes.

Now that I think about it, we absolutely do advise to use MongoDB, because it’s MUCH MUCH more stable.

It resolved many headaches for me and others.

Are you still on the json path and want to move to Mongo?

**Comment by GlassedSilver** [comment]
> The [docker-compose.yml](https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/master/docker-compose.yml) does not work for me when attempting to use mongo.
> 
> ```
> getaddrinfo EAI_AGAIN ytdl-mongo-db
> ECONNREFUSED 127.0.0.1:27017
> Failed to connect to MongoDB, using Local DB as a fallback. Make sure your MongoDB instance is accessible, or set Local DB as a default through the config.
> ```
> 
>  ```
> version: "2"
> services:
>     ytdl_material:
>         environment: 
>             ALLOW_CONFIG_MUTATIONS: 'true'
>             ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
>             ytdl_use_local_db: 'false'
>             write_ytdl_config: 'true'
>         restart: always
>         depends_on:
>             - ytdl-mongo-db
>         volumes:
>             - ./appdata:/app/appdata
>             - ./audio:/app/audio
>             - ./video:/app/video
>             - ./subscriptions:/app/subscriptions
>             - ./users:/app/users
>         ports:
>             - "8998:17442"
>         image: tzahi12345/youtubedl-material:nightly
>     ytdl-mongo-db:
>         image: mongo
>         ports:
>             - "27017:27017"
>         logging:
>             driver: "none"          
>         container_name: mongo-db
>         restart: always
>         volumes:
>             - ./db/:/data/db
> ```

Found the issue.

Change MongoDB’s container name to `ytdl-mongo-db` so it matches the URL passed to YTDL-M container configs, so that it looks like this:

```
version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:nightly
    ytdl-mongo-db:
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: "none"          
        container_name: ytdl-mongo-db
        restart: always
        volumes:
            - ./db/:/data/db
```

I will make a PR to fix this inconsistency.

Sometimes it takes a while and some distance to spot these sorts of issues. (I personally deployed differently, so my working setup never challenged this docker-compose.yml.
