### ISSUE TITLE
[BUG] LDAP error in logs

### ISSUE THREAD

**Issue by lgwapnitsky** [Tzahi12345/YoutubeDL-Material#617]
I've just installed the latest version, and am attempting to configure LDAP.  The only error that appears in the logs is 'username not found', but I am using a valid DC and credentials. Is there a way to get more log information to determine wherein the error lies?

1. Configure LDAP
2. Attempt to log in using LDAP
3. Login fails

**Expected behavior**
Successful login

**Comment by GlassedSilver** [comment]
Need to know what your environment looks like.

How did you install YTDL-M?

How did you install your LDAP server?

By default, YTDL-M will connect to an LDAP server through localhost:389, which, if you run YTDL-M in a container really only means that very container.

If your LDAP server is on the same machine in another container you will need to configure differently.

That being said, whilst I don't run an LDAP myself, you should really provide more information, so we can actually help you.

@Tzahi12345 might know more about this sort of setup, but I'll try my best as well. 👍

**Comment by martadinata666** [comment]
So i tried to setup a LDAP to use the login function i say it prety rough on the how to setup as minimal hint to get with.
1. First on bind CN it only `cn=root` as it must givin hint `cn=xxx,ou=yyy,dc=vvv,dc=zzz`
2. And the bind Credential shot in plain sight, even it just show in admin page.
3. Like number one, the search base also just givin minimal hint.
4. In simple terms not enough hint what to fill at input box.

![2022-06-14-191709_304x443_scrot](https://user-images.githubusercontent.com/2433562/173577392-cd894bc9-1603-4e61-876c-d45770634114.png)

LDAP Compose
```
version: "3.8"
services:
  app:
    image: martadinata666/lldap:latest
    restart: unless-stopped
    ports:
      # For LDAP
      - "3890:3890"
      # For the web front-end
      - "17170:17170"
    volumes:
      - ./data:/data
    environment:
      - LLDAP_JWT_SECRET=thisisjwtsecret
      - LLDAP_LDAP_USER_PASS=ldappass
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
```
