### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by saschafoerster** [Tzahi12345/YoutubeDL-Material#670]
I am trying to upgrade my docker-installation on a Synology NAS from 4.2 to 4.3. 

My docker-compose.yml: 

```
version: "2"
services:
    ytdl_material:
        environment:
            ALLOW_CONFIG_MUTATIONS: 'true'
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'true'
            write_ytdl_config: 'true'
            ytdl_twitch_client_id: ''
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:4.3
    ytdl-mongo-db:
        image: mongo:4
        ports:
            - "27017:27017"
        logging:
            driver: "none"
        container_name: mongo-db
        restart: always
        volumes:
            - ./db/:/data/db
```

I switched the image from 4.2 to 4.3, then I get this error message: 

```
$ docker-compose up
mongo-db is up-to-date
Recreating 97ed7c2ab8fb_youtube-dl_ytdl_material_1 ... done
Attaching to youtube-dl_ytdl_material_1
ytdl_material_1  | 
ytdl_material_1  | > backend@1.0.0 start
ytdl_material_1  | > pm2-runtime --raw pm2.config.js
ytdl_material_1  | 
ytdl_material_1  | 2022-06-27T07:21:30: PM2 log: Launching in no daemon mode
ytdl_material_1  | 2022-06-27T07:21:30: PM2 log: [Watch] Start watching YoutubeDL-Material
ytdl_material_1  | 2022-06-27T07:21:30: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
ytdl_material_1  | 2022-06-27T07:21:30: PM2 log: App [YoutubeDL-Material:0] online
ytdl_material_1  | 2022-06-27T07:21:37.961Z INFO: Config items set using ENV variables.
ytdl_material_1  | 2022-06-27T07:21:38.222Z INFO: Beginning migration: 4.2->4.3+
ytdl_material_1  | TypeError: Cannot read properties of undefined (reading 'map')
ytdl_material_1  |     at createFilesRecords (/app/db.js:928:57)
ytdl_material_1  |     at Object.exports.generateJSONTables (/app/db.js:895:24)
ytdl_material_1  |     at Object.exports.importJSONToDB (/app/db.js:911:38)
ytdl_material_1  |     at async checkMigrations (/app/app.js:189:23)
ytdl_material_1  |     at async loadConfig (/app/app.js:511:5)
ytdl_material_1  |     at async setAndLoadConfig (/app/app.js:482:5)
```
I am ready to give more details, but maybe someone can guide me into a direction where to search for an error.
