### ISSUE TITLE
[BUG] v.4.3 docker fails to start with exit code 243

### ISSUE THREAD

**Issue by AlexFullmoon** [Tzahi12345/YoutubeDL-Material#671]
**Describe the bug**
Docker-compose file that ran previous nightly (nightly-2022-06-22) fine, stops immediately on 4.3 with code 243

```yaml
version: "3.5"

services:
  ytdl_material:
#    image: tzahi12345/youtubedl-material:nightly-2022-06-22
    image: tzahi12345/youtubedl-material:4.3
    container_name: ytdl_material
    environment: 
      ALLOW_CONFIG_MUTATIONS: 'true'
      write_ytdl_config: 'true'
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      ytdl_port: 9998
      UID: 1026
      GID: 100
    volumes:
      - /volume1/docker/youtube-dlm/appdata:/app/appdata
      - /volume1/video/YoutubeAudio:/app/audio
      - /volume1/video/YoutubeDLM/Singles:/app/video
      - /volume1/video/YoutubeDLM:/app/subscriptions
    ports:
      - 9998:9998/tcp
    networks:
      - ytdl
    depends_on:
      - ytdl-mongo-db
    restart: "no"
      
  ytdl-mongo-db:
    image: mongo:4
    container_name: mongo-db
    ports:
      - 27017:27017
    networks:
      - ytdl
    logging:
      driver: "none"
    volumes:
        - /volume1/docker/youtube-dlm/db/:/data/db
    restart: always
    
networks:
  ytdl:
    name: ytdl
```

**Environment**
- Version 4.3
- Docker tag: latest/4.3
- Docker tag nightly-2022-06-22 works

From https://github.com/Tzahi12345/YoutubeDL-Material/pull/117 I assume that error code is related to node/npm.
