### ISSUE TITLE
[BUG] Javascript heap out of memory

### ISSUE THREAD

**Issue by Bastians-Bits** [Tzahi12345/YoutubeDL-Material#697]
**Describe the bug**
When trying to download a lot of videos (1030) the application crashes and restarts.

**To Reproduce**
1. Go to 'Downloads'
2. Click on 'Resume all downloads'

**Expected behavior**

**Screenshots**
```
<--- Last few GCs --->
[38:0x4aaa6a0] 21936516 ms: Scavenge 4022.1 (4117.8) -> 4021.7 (4128.6) MB, 12.2 / 0.0 ms  (average mu = 0.509, current mu = 0.383) allocation failure 
[38:0x4aaa6a0] 21936575 ms: Scavenge 4028.4 (4128.6) -> 4027.7 (4129.6) MB, 16.1 / 0.0 ms  (average mu = 0.509, current mu = 0.383) allocation failure 
[38:0x4aaa6a0] 21937225 ms: Scavenge 4029.4 (4129.6) -> 4028.6 (4150.3) MB, 643.6 / 0.0 ms  (average mu = 0.509, current mu = 0.383) allocation failure 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [node /app/app.js]
 2: 0xa1c193 node::FatalError(char const*, char const*) [node /app/app.js]
 3: 0xcf8dde v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node /app/app.js]
 4: 0xcf9157 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node /app/app.js]
 5: 0xeb09f5  [node /app/app.js]
 6: 0xec06bd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node /app/app.js]
 7: 0xec33be v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node /app/app.js]
 8: 0xe84632 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node /app/app.js]
 9: 0xe7cc44 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node /app/app.js]
10: 0xe7e950 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [node /app/app.js]
11: 0xe8678d v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [node /app/app.js]
12: 0xd079a5 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node /app/app.js]
13: 0xbf5619  [node /app/app.js]
14: 0xae4c96  [node /app/app.js]
15: 0x1586c6c  [node /app/app.js]
2022-07-03T08:42:38: PM2 log: App [YoutubeDL-Material:0] exited with code [0] via signal [SIGABRT]
2022-07-03T08:42:38: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2022-07-03T08:42:38: PM2 log: App [YoutubeDL-Material:0] online
2022-07-03T06:42:39.760Z INFO: Config items set using ENV variables.
2022-07-03T06:42:40.290Z INFO: YoutubeDL-Material v4.3 started on PORT 17442
```

**Environment**
```
Installed version: v4.3

Installation type: docker 
Docker tag: nightly 
Commit hash: b827f8f 
Build date: 2022-06-30

Docker version 20.10.14, build a224086
```

**Additional context**
I am trying to download a videos of this channel: https://www.youtube.com/c/CalebHyles
I am using a MongoDB as database.

**Comment by Tzahi12345** [comment]
Looks like you're running out of memory. Can you try adding the following into your docker-compose environment:

```
NODE_OPTIONS: --max_old_space_size=2048
```

So it should look something like:

```
version: "2"
services:
    ytdl_material:
        environment: 
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
            NODE_OPTIONS: --max_old_space_size=2048
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest
    ytdl-mongo-db:
        image: mongo
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - ./db/:/data/db
```

It seems like the solution is to limit how much memory the backend can consume, but it probably comes with performance downsides.
