### ISSUE TITLE
Running UID/GID for the docker

### ISSUE THREAD

**Issue by chimlm** [Tzahi12345/YoutubeDL-Material#72]
I run the docker version of this and over ride the UID/GID with docker run command. However this is causing permission problem when the docker try to download the latest youtube-dl package.

As it is a common practice to not run docker as root user, the fixed could be changing the write permission of "modules/youtube-dl/bin/" folder.

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

[Error: EACCES: permission denied, open 'node_modules/youtube-dl/bin/youtube-dl'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'node_modules/youtube-dl/bin/youtube-dl'
}

**Comment by Tzahi12345** [comment]
Interesting, I think this could be solved by chmodding the `node_modules/youtube-dl/bin` folder on startup. I can't do much else as I don't have full control over that folder (it's a dependency), but I think that might solve it.

I'm not sure I want to do this in all cases so I might set up an environment variable to control it. Something like YTDL_CUSTOM_UID_GID. If any other problems arise because of a custom uid/gid, I can let the fix use the same environment variable so the environment variables don't add up.

I'll play around with this a bit more and see if I get any solutions to it.

**Comment by chimlm** [comment]
For docker image, better practice is to update a dependency in a separate layer rather than changing it inside a running container.

**Comment by Tzahi12345** [comment]
This issue has been solved thanks to @SuperSandro2000 and @Wonderfall's hard work! Here's the [merged PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/116). You can set the UID/GUID using ENV vars and it should work without issue. Thanks for the bug report!

**Comment by robflate** [comment]
Sorry, can someone give an example of how to set these ENV vars in docker compose. I've done;

```
environment:
  - UID=501
  - GUID: 999
```

but downloads are still owned by root. I also tried `GID` instead of `GUID`.

**Comment by SuperSandro2000** [comment]
use either 
```
environment:
  UID: 501
  GUID: 999
```
or 
```
environment:
  - UID=501
  - GUID=999
```


You cant mix them.

**Comment by robflate** [comment]
Sorry that was a typo when writing it here. My compose file contains;
```
youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    restart: unless-stopped
    ports:
      - 17442:17442
    volumes:
      - path/to/youtubedl-material/appdata:/app/appdata
      - path/to/youtubedl-material/audio:/app/audio
      - path/to/youtubedl-material/video:/app/video
      - path/to/youtubedl-material/subscriptions:/app/subscriptions
      - path/to/youtubedl-material/users:/app/users
    environment:
      UID: 501
      GUID: 999
```
All the files downloaded to my bind mount folder are owned by root:root not the user passed in the ENV vars.
