### ISSUE TITLE
[BUG] Download a playlist will only downoload one video/audio.

### ISSUE THREAD

**Issue by tiritibambix** [Tzahi12345/YoutubeDL-Material#782]
**Describe the bug**
Input a playlist URL or subscribing to a playlist will only downoload one video/audio (the first)

**To Reproduce**
1. Go to home
2. Paste https://www.youtube.com/watch?v=EH111yTNRTQ&list=PL2At1KtEs2fLtG1E1KHBI1AvRr6t2vK1a
3. (optional) click on audio only for faster results

**Expected behavior**
All videos/audios to be downloaded

**Environment**
Installation type: docker
Docker tag: latest
Commit hash: fc3c179
Build date: 2022-07-05 

**Additional context**
Here is my docker-compose:
```
version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: unless-stopped
        depends_on:
            - ytdl-mongo-db
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - .L/subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest
    ytdl-mongo-db:
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: "none"          
        container_name: ytdl-mongo-db
        restart: unless-stopped
        volumes:
            - ./db/:/data/db
```
