### ISSUE TITLE
[BUG] Docker version - mongodb restarting

### ISSUE THREAD

**Issue by S474N** [Tzahi12345/YoutubeDL-Material#884]
**Describe the bug**
Mongo-db container still restarting.

**Screenshots**
![image](https://user-images.githubusercontent.com/16512337/235297304-da325ee2-f151-4191-8efd-4850aff72ee1.png)

**Environment**
Nainstalovaná verze: v4.3 -   You are up to date.
Installation type: docker
Docker tag: latest
Commit hash: fc3c179
Build date: 2022-07-05

Raspberry Pi 4B, Raspbian
Linux rpi4b 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux

**Additional context**
docker-compose.yml:
```
 ytdl:
    container_name: ytdl
    image: tzahi12345/youtubedl-material:latest
    environment:
        ALLOW_CONFIG_MUTATIONS: 'true'
        ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
        ytdl_use_local_db: 'false'
        write_ytdl_config: 'true'
    restart: always
    depends_on:
        - ytdl-mongo-db
    volumes:
        - ./volumes/ytdl/appdata:/app/appdata
        - ~/YT-DL/audio:/app/audio
        - ~/YT-DL/video:/app/video
        - ./volumes/ytdl/subscriptions:/app/subscriptions
        - ./volumes/ytdl/users:/app/users
    ports:
        - "8998:17442"

  ytdl-mongo-db:
    container_name: mongo-db
    image: mongo:4.4.6
    ports:
        - "27017:27017"
#    logging:
#        driver: "none"
    restart: always
    volumes:
        - ~/YT-DL/db/:/data/db

```
tested also with image` mongo:4` and nothing changed.

**Comment by martadinata666** [comment]
`mongo:4.4.6` wont get that cpu features log and start correctly. Likely you are on `mongo:4` that lead to `4.4.21` and starting `4.4.19` also need that CPU feature blocker. So last version without CPU features block `4.4.18`

**Comment by S474N** [comment]
Updated firmware to:
`Linux rpi4b 6.1.25-v8+ #1647 SMP PREEMPT Wed Apr 26 17:39:08 BST 2023 aarch64 GNU/Linux`

Used: `mongo:4.4.18`

And everything seems to be ok.

What to put on the main page of the project warning for the use of docker version on rpi?

**Comment by Tzahi12345** [comment]
We do have documentation on this, it's just probably not visible enough: https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Raspberry-Pi-4

**Comment by S474N** [comment]
But I had 4.4.6 for many months but today had problem with it. 4.4.18 solved my problem.

**Comment by Tzahi12345** [comment]
Oh I must have missed that, I'll update the existing docs. Not sure if we need to start making a separate docker-compose for different setups but that could get tedious.

**Comment by GlassedSilver** [comment]
offtopic/meta:
docker label is for pull requests only 😛
Sorry for the confusion, we need it for some automation if memory serves.

On another note: the docker compose file is just a generic example that SHOULD work for most people, if you have some setup that's a bit more special you're kinda signing up for at least having to ask for help here and there.

That being said, I guess in the case of Raspberry Pi it's fair to acknowledge common pitfalls in the same docker compose comments?

**Comment by martadinata666** [comment]
every cpu that don't have avx support, Intel pentium series from coffee lake and under, syno/qnap devices due arm cpu and again J series cpu with don't have avx, or any other may be not seen right now.

**Comment by Tzahi12345** [comment]
@GlassedSilver

Haha didn't know that... Anyways, I added a comment: https://github.com/Tzahi12345/YoutubeDL-Material/commit/b859d08d86077a91de19a8a9c7130dfd3660c775. With that we can probably close this issue.

@martadinata666 

I thought `mongo:4` resolves the avx missing errors? That's the current docker-compose

**Comment by martadinata666** [comment]
the newer `mongo:4` mean 4.4.21 need avx, latest without avx `4.4.18` about 2/3 months ago. I think as people usually look on `docker-compose.yml`, set default database to `mongo:4.4.18` if they assure that the CPU support avx use `mongo:5`, at least we ensure that this kind of thread not repeating.

```
    ytdl-mongo-db:
        # Replace to mongo:5 or mongo:4, ensure your CPU support AVX instruction first, read
        # https://www.mongodb.com/docs/manual/administration/production-notes/#x86_64
        # https://www.mongodb.com/docs/manual/administration/production-notes/#arm64
        image: mongo:4.4.18        
        container_name: mongo-db
        restart: always
        volumes:
            - ./db/:/data/db

```
