### ISSUE TITLE
[BUG] TwitchChat downloads wrong relative directory

### ISSUE THREAD

**Issue by JrdnRgrs** [Tzahi12345/YoutubeDL-Material#994]
**Describe the bug**
When I try to use the 'Download Twitch Chat' feature, it seems as though the downloaded data is not getting saved to the correct path. In my logs I see the command it is trying to run ` cmd: 'TwitchDownloaderCLI chatdownload -u 1879140551 -o appdata/1879140551.json',` but then i get an error once it downloads `Access to the path '/usr/local/bin/appdata'  is denied`. I tried manually running the command with the correct absolute path `TwitchDownloaderCLI chatdownload -u 1879140551 -o /app/appdata/1879140551.json` and the interface was finally able to pick up and see the data. 

**To Reproduce**
1. Download a twitch VOD (im using [this vod](https://www.twitch.tv/videos/1879140551) for testing the download since it is very short)
2. View the video in the UI once it has been downloaded
3. Click Download Twitch Chat
4. See error in the logs, after sometime UI says chat cannot be downloaded.

**Expected behavior**
Twitch chat should be downloaded to the correct path and then be loaded on one click

**Screenshots**
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/6921992/377fdd0d-5aa7-497c-a994-3abaf74fa8c3)

**Environment**
- YoutubeDL-Material version: v4.3.2
- Docker tag: nightly

Installed version: v4.3.2 -  Checking for updates...  
Installation type: docker
Docker tag: nightly
Commit hash: 99c5cf5
Build date: 2023-08-15

**Additional context**
I'm running this in a docker compose stack on a raspberry pi. I am using the correct database tag for my pi. I'll also mention that I had trouble actually getting any video to download at all until i went into the container and ran `chmod +x /app/node_modules/youtube-dl/bin/youtube-dl` or else I was constantly getting the error: `Error: Command failed with EACCES: node_modules/youtube-dl/bin/youtube-dl`. 

here's my compose file, although im not sure if it matters too much in this case

```
version: "3"
services:
    ytdl_material:
        container_name: ytdl
        environment:
            - ytdl_mongodb_connection_string
            - ytdl_use_local_db
            - write_ytdl_config
            - UID
            - GID
        restart: always
        networks:
          - ytdl
          - shared
        depends_on:
            - ytdl-mongo-db
        volumes:
            - /media/Library/docker/yt-dl/appdata:/app/appdata
            - /media/Library/docker/yt-dl/audio:/app/audio
            - /media/Library/docker/yt-dl/video:/app/video
            - /media/Library/docker/yt-dl/subscriptions:/app/subscriptions
            - /media/Library/docker/yt-dl/users:/app/users
        #ports:
        #    - "8998:17442"
        image: tzahi12345/youtubedl-material:nightly
    ytdl-mongo-db:
        # If you are using a Raspberry Pi, use mongo:4.4.18
        image: mongo:4.4.18
        logging:
            driver: "none"
        container_name: ytdl-db
        restart: always
        networks:
          - ytdl
        volumes:
            - /media/Library/docker/yt-dl/db/:/data/db

networks:
  ytdl:
  shared:
    external: true
    name: shared
```
