### ISSUE TITLE
[BUG] youtube-dl doesn't have exec perms in latest nightly build

### ISSUE THREAD

**Issue by zkhcohen** [Tzahi12345/YoutubeDL-Material#997]
**Describe the bug**
`/app/node_modules/youtube-dl/bin/youtube-dl` is missing exec perms as of 99c5cf5, causing downloads to fail with:

`Error while retrieving info on video with URL <URL REDACTED> with the following message: Error: Command failed with EACCES: node_modules/youtube-dl/bin/youtube-dl -o audio/%(title)s.%(ext)s --write-info-json --audio-quality 0 -x --audio-format mp3 --write-thumbnail --no-clean-info-json -j --dump-json <URL REDACTED> spawn node_modules/youtube-dl/bin/youtube-dl EACCES `

I haven't traced the root cause back to a particular change yet, but I can confirm that the exec perm is added in the v4.3.2 tag, and downloads work as expected.

**To Reproduce**
1. Set your Docker image to `tzahi12345/youtubedl-material:nightly`.
2. Attempt to download YouTube video.

**Expected behavior**
The youtube-dl program should have executable permissions, allowing YouTube videos to be downloaded.

**Environment**

**PLEASE NOTE my UID/GID below...**

docker-compose.yml:
```
 ytdl-material:
    image: tzahi12345/youtubedl-material:nightly
    container_name: ytdl-material
    environment:
      UID: "99"
      GID: "100"
      ALLOW_CONFIG_MUTATIONS: "true"
```
